language: php
php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - hhvm

matrix:
    fast_finish: true

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
        - vendor

before_script:
    # Create php.ini & sections.ini
    - cp ./tests/config.sample.neon ./tests/config.neon
    - cp ./tests/php-unix.ini ./tests/php.ini

    - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then cat ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini >> ./tests/php.ini; fi
    - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then NTESTER_FLAGS="--coverage ./coverage.xml --coverage-src ./src"; else TESTER_FLAGS=""; fi

    - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then cp ./tests/sections.hhvm.ini ./tests/sections.ini; fi
    - if ! [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then cp ./tests/sections.sample.ini ./tests/sections.ini; fi

    # Create MySQL & Postgre database
    - psql -c 'CREATE DATABASE nextras_orm_test' -U postgres
    - mysql -e 'CREATE DATABASE nextras_orm_test;'

    - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql

    # Install Nette Tester
    - if ! [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then phpenv config-rm xdebug.ini; fi
    - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then composer require --dev jakub-onderka/php-parallel-lint:~0.9.2; fi
    - travis_retry composer update --no-interaction --prefer-source

script:
    - ./tests/run.sh -s $NTESTER_FLAGS ./tests/cases
    - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then vendor/bin/parallel-lint src tests/cases; fi

after_script:
    - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      && php coveralls.phar --verbose --config tests/.coveralls.yml
      || true;
      fi

after_failure:
    # Print *.actual content & log content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
    - for i in $(find tests -name \*.log); do echo "--- $i"; cat $i; echo; echo; done
